In [1]:
import numpy as np
np.__version__

'1.13.1'

In [2]:
import numpy as np

In [3]:
np?

In [4]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [5]:
np.array([3.45,5,6,7])

array([ 3.45,  5.  ,  6.  ,  7.  ])

In [8]:
np.array([range(i,i+3) for i in [3,5,7]])

array([[3, 4, 5],
       [5, 6, 7],
       [7, 8, 9]])

In [13]:
np.random.seed(0)
# random mot int array co 6 phan tu trong khoang tu 0 den 10
x1 = np.random.randint(10,size=6)
# random mot int array 2 chieu, moi chieu co 3 hang 4 cot
x2 = np.random.randint(10,size=(3,4))
# random 1 int array co 3 chieu, moi chieu co 4 hang 5 cot
x3 = np.random.randint(10,size=(3,4,5))
print(x1)
print(x2)
print(x3)

[5 0 3 3 7 9]
[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]


In [14]:
x1[0]

5

In [20]:
# Lay ra phan tu o hang thu 3, cot thu 4. Vi bat dau dem tu 0 nen phai goi la x2[2,3]
x2[2,3]

7

In [23]:
# Lay ra phan tu o hang thu 4, cot thu 4 tai chieu thu 3. Vi bat dau dem tu 0 nen phai goi la x3[2,3,3]
x3[2,3,3]

6

Array Slicing x[start:stop:step]